// @ts-nocheck

// Domain category: memory-checkpoint lifecycle handler (maybeCheckpointWithGating).
// Extracted from handlers.ts as a dependency-injected *WithGating* function.

import type { MessageWithParts } from "./constants.ts"
import { CHECKPOINT_MARKER, MIN_TERMINAL_MESSAGES_BEFORE_CHECKPOINT, CHECKPOINT_MODES } from "./constants.ts"
import { isAssistantStop } from "./analysis.ts"
import { hasUsefulPayload, endsMidIntent } from "./pure-helpers.ts"

// Returns true if a checkpoint prompt was issued. Idle-only, once per session,
// and only on a genuinely complete turn so it never fires over a stall.
export async function maybeCheckpointWithGating(args: {
  sid: string
  last: MessageWithParts
  checkpointedSessions: Set<string>
  terminalCountBySession: Map<string, number>
  checkpointDisabledAgents: Set<string>
  client: any
  directory: string
  getPromptRouting: (...candidates: Array<MessageWithParts | null | undefined>) => { agent?: string; model?: { providerID: string; modelID: string } }
}): Promise<boolean> {
  const { sid, last } = args
  if (args.checkpointedSessions.has(sid)) return false

  const mode = String(last?.info?.mode ?? "")
  if (!CHECKPOINT_MODES.has(mode)) return false

  const count = args.terminalCountBySession.get(sid) ?? 0
  if (count < MIN_TERMINAL_MESSAGES_BEFORE_CHECKPOINT) return false

  // Only checkpoint after a clean, SUCCESSFUL turn — a real stop with useful
  // output, not a stall and not mid-intent. (Do NOT require a final-review
  // signal: that is a build-mode convention and would block checkpoints in
  // plan mode. On idle, retry already owns build stalls, so reaching here
  // means the turn completed.)
  if (!isAssistantStop(last)) return false
  if (endsMidIntent(last)) return false
  if (!hasUsefulPayload(last)) return false

  // Utility subagents never checkpoint: they do no durable work of their own,
  // and a checkpoint prompt would only burn a turn on them.
  const routing = args.getPromptRouting(last)
  const currentAgent = String(routing.agent ?? "").trim().toLowerCase()
  if (currentAgent && args.checkpointDisabledAgents.has(currentAgent)) {
    console.log(`[turn-guard] checkpoint skipped for sid=${sid}: agent=${currentAgent} is in checkpoint.disabledAgents`)
    return false
  }

  args.checkpointedSessions.add(sid)
  console.log(`[turn-guard] prompting memory checkpoint for sid=${sid} (mode=${mode})`)

  try {
    const body: any = {
      parts: [
        {
          type: "text",
          text:
            `${CHECKPOINT_MARKER} Before this session winds down, run a two-part memory ` +
            `check. These are independent — answer both; either can warrant saving alone.\n\n` +
            `PART 1 — did durable STATE change? (the always-loaded blocks)\n` +
            `- project-state — architecture, active work, or a major decision changed?\n` +
            `- active-conventions — a naming/style/structural/tooling rule changed?\n` +
            `- user-preferences — a new durable preference was stated?\n` +
            `For each durable STATE change, write/update it via diary_write (derived memory ` +
            `writes like add_drawer/kg_add are dreamer-only; write-authority will reject them from ` +
            `this agent — diary_write is the correct tool here, and a dreamer consolidation pass ` +
            `formalizes it into the derived layer).\n` +
            `mem-core is a deterministic file-only render regenerated by the consolidation runtime from derived memory. ` +
            `Do NOT hand-edit mem-core files and do NOT write any context-blocks drawer for mem-core.\n\n` +
            `PART 2 — was substantive WORK done or something LEARNED? (diary / worked example)\n` +
            `This applies EVEN IF no block changed. Save a derived entry if any happened:\n` +
            `- a feature/fix was implemented (what was built, where, key choices),\n` +
            `- a bug's root cause was found (the cause, not just the fix),\n` +
            `- a non-obvious "how/why this works" was discovered,\n` +
            `- a problem was solved in a reusable way (file as a worked example in the ` +
            `apprenticeship room; if the reusable solution maps to a RECURRING TASK, also add one line ` +
            `\`SKILL_EXERCISED: <concept name>\` so a later consolidation pass can link the worked ` +
            `example to the skill it exercised — this is only a signal for the dreamer, never a write),\n` +
            `- a dead end worth not repeating was hit.\n` +
            `Use diary_write (the apprenticeship room included) for all of this. Synthesize — ` +
            `don't dump a transcript; write what a future session would want to retrieve. ` +
            `Lead each saved entry with a one-line \`DESC:\` (what it is + when it's ` +
            `relevant) so it's discoverable without loading the body.\n\n` +
            `IF this session's work appears to already be done / already correct / a ` +
            `continuation of prior work: do NOT assume a prior session already saved it. ` +
            `You cannot see whether that happened. SEARCH MemPalace (diary/drawers) for an ` +
            `entry covering this specific work before concluding nothing needs saving. ` +
            `If you find a matching entry: genuinely a no-op, say so and cite what you found. ` +
            `If you find NO matching entry: this is unsaved work regardless of which session ` +
            `did it — save it now per PART 2 above. Never write "a previous session should ` +
            `have handled this" without having searched and found evidence it did.\n\n` +
            `Do not invent changes just to have something to write — but "no block changed" ` +
            `is NOT "nothing to save"; implementation work and discoveries belong in PART 2. ` +
            `If genuinely nothing in either part, reply "No memory updates needed" and stop. ` +
            `End by listing what you saved under each part.`,
        },
      ],
    }
    if (routing.agent) body.agent = routing.agent
    if (routing.model) body.model = routing.model

    await args.client.session.prompt({
      path: { id: sid },
      query: { directory: args.directory },
      body,
    })
  } catch (err) {
    console.error("[turn-guard] failed to issue checkpoint prompt:", err)
    return false
  }

  return true
}
