/**
 * The end-of-session memory-checkpoint prompt.
 *
 * Shared verbatim by both surfaces: OpenCode issues it as a follow-up turn via
 * `client.session.prompt` (prefixed with `CHECKPOINT_MARKER` so its reply is
 * recognised as terminal and never retried), omp returns it as the
 * `additionalContext` of a `session_stop` continuation. The wording is the
 * policy, so it lives here rather than in either adapter.
 */

export const CHECKPOINT_PROMPT =
  `Before this session winds down, run a two-part memory ` +
  `check. These are independent — answer both; either can warrant saving alone.\n\n` +
  `PART 1 — did durable STATE change? (the always-loaded blocks)\n` +
  `- project-state — architecture, active work, or a major decision changed?\n` +
  `- active-conventions — a naming/style/structural/tooling rule changed?\n` +
  `- user-preferences — a new durable preference was stated?\n` +
  `For each durable STATE change, write/update it via diary_write (derived memory ` +
  `writes like add_drawer/kg_add require lineage-bearing node creation through the synthesis ` +
  `boundary (node-type authority), so this agent should use diary_write; a consolidation pass ` +
  `formalizes it into the derived layer).\n` +
  `mem-core is a deterministic file-only render regenerated by the consolidation runtime from derived memory. ` +
  `Do NOT hand-edit mem-core files and do NOT write any context-blocks drawer for mem-core.\n\n` +
  `PART 2 — was substantive WORK done or something LEARNED? (diary / worked example)\n` +
  `This applies EVEN IF no block changed. Save a derived entry if any happened:\n` +
  `- a feature/fix was implemented (what was built, where, key choices),\n` +
  `- a bug's root cause was found (the cause, not just the fix),\n` +
  `- a non-obvious "how/why this works" was discovered,\n` +
  `- a problem was solved in a reusable way (file as a worked example in the ` +
  `apprenticeship room; if the reusable solution maps to a RECURRING TASK, also add one line ` +
  `\`SKILL_EXERCISED: <concept name>\` so a later consolidation pass can link the worked ` +
  `example to the skill it exercised — this is only a signal for the dreamer, never a write),\n` +
  `- a dead end worth not repeating was hit.\n` +
  `Use diary_write (the apprenticeship room included) for all of this. Synthesize — ` +
  `don't dump a transcript; write what a future session would want to retrieve. ` +
  `Lead each saved entry with a one-line \`DESC:\` (what it is + when it's ` +
  `relevant) so it's discoverable without loading the body.\n\n` +
  `IF this session's work appears to already be done / already correct / a ` +
  `continuation of prior work: do NOT assume a prior session already saved it. ` +
  `You cannot see whether that happened. SEARCH MemPalace (diary/drawers) for an ` +
  `entry covering this specific work before concluding nothing needs saving. ` +
  `If you find a matching entry: genuinely a no-op, say so and cite what you found. ` +
  `If you find NO matching entry: this is unsaved work regardless of which session ` +
  `did it — save it now per PART 2 above. Never write "a previous session should ` +
  `have handled this" without having searched and found evidence it did.\n\n` +
  `Do not invent changes just to have something to write — but "no block changed" ` +
  `is NOT "nothing to save"; implementation work and discoveries belong in PART 2. ` +
  `If genuinely nothing in either part, reply "No memory updates needed" and stop. ` +
  `End by listing what you saved under each part.`;

/** Assistant turns a session must have produced before a checkpoint is worth spending. */
export const MIN_TURNS_BEFORE_CHECKPOINT = 4;
